### ISSUE TITLE
Ready for CodeIgniter

### ISSUE THREAD

**Issue by joel-depiltech** [joshtronic/php-holidayapi#2]
Hello,

A little message to warn you about a CodeIgniter library I created with your work : https://github.com/joel-depiltech/codeigniter-holidayapi

And I posted it also on packagist: https://packagist.org/packages/joel-depiltech/codeigniter-holidayapi

Regards,
Joël

**Comment by joshtronic** [comment]
This is fantastic!! Mind if I list it on the HAPI site?

**Comment by joel-depiltech** [comment]
Sure ! I will be glad if you mention my library on your website.

**Comment by defro** [comment]
The goal of this issue is just to announce the existence of your code on CodeIgniter. Feel free to class this issue when you want...

**Comment by joshtronic** [comment]
Wow, seems I spaced on adding this to the site. It's slated for release, next deploy will include it :)

Thanks again!
